name: Deploy to Hostinger via FTP
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload via FTP (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: .
          server-dir: public_html
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/*.md  
